name: Publish to Qiita

on:
  push:
    branches:
      - main  # メインブランチ名に合わせて変更してください（masterの場合もあり）
    paths:
      - 'public/articles**' # publicフォルダ内の変更時のみ実行

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install qiita-cli
        run: npm install -g @qiita/qiita-cli

      - name: Publish articles
        run: npx qiita publish --all
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}